Design of supporting ALB to expose service workbench website without domain
awslabs/service-workbench-on-aws-cn pull request #118
Opened 2022-11-19 15:54 UTC by dengmingtong

…domain

Issue #, if available:

Description of changes:

Checklist:

- [ ] Have you successfully deployed to an AWS account with your changes?
- [ ] Have you successfully deployed to an AWS China account with your changes?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully tested with your changes locally?
- [ ] If new dependencies have been added, have they been pinned to specific versions?
- [ ] Is this change also required on the AWS Solution version?
- [ ] Have you updated openapi.yaml if you made updates to API definition (including add, delete or update parameter and request data schema)?
- [ ] If you had to run manual tests, have you considered automating those tests by adding them to [end-to-end tests](../main/end-to-end-tests/README.md)?
- [ ] If you are updating the changelog and vending out a new release, have you updated versionNumber and versionDate in [.defaults.yml](../main/config/settings/.defaults.yml)

AS review ticket id:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-21 08:21 UTC, zxkane requested changes

2022-11-21 08:21 UTC, zxkane commented on rfcs/alb_expose_portal/index.md
> +This RFC proposes is to design a new architecture to make service workbench can be deployed and used in china regions without ICP domain.
add scenario,

- deploy the entire solution inside VPC with secure network access

2022-11-21 08:21 UTC, zxkane commented on rfcs/alb_expose_portal/index.md
> +In china regions, when users input the url of service workbench into browser, such as https://example-serviceworkbench.com, these requests are sent to cloudfront through domain name resolution, then
then forward request to S3 to get static files, such as html, css and js files.

-> add `while the cache is missing`

2022-11-21 08:21 UTC, zxkane commented on rfcs/alb_expose_portal/index.md
> +![existing-deployment](./existing-deployment.drawio.png)
might add a new line here for rendering version

2022-11-21 08:21 UTC, zxkane commented on rfcs/alb_expose_portal/index.md
> +Lambda is a compute service that lets you run code without provisioning or managing servers. Lambda runs your code on a high-availability compute infrastructure and performs all of the administration
`container image` might be better

https://docs.aws.amazon.com/lambda/latest/dg/images-create.html

2022-11-21 08:21 UTC, zxkane commented on rfcs/alb_expose_portal/index.md
> +The maximum size of the response body that the Lambda function can send is 1 MB to ALB [Limitation}(https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html). So we n
markdown syntax is wrong

2022-11-21 13:36 UTC, dengmingtong commented on rfcs/alb_expose_portal/index.md
> +The maximum size of the response body that the Lambda function can send is 1 MB to ALB [Limitation}(https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html). So we n
Fixed

2022-11-21 13:37 UTC, dengmingtong commented on rfcs/alb_expose_portal/index.md
> +Lambda is a compute service that lets you run code without provisioning or managing servers. Lambda runs your code on a high-availability compute infrastructure and performs all of the administration
Fixed

2022-11-21 13:37 UTC, dengmingtong commented on rfcs/alb_expose_portal/index.md
> +In china regions, when users input the url of service workbench into browser, such as https://example-serviceworkbench.com, these requests are sent to cloudfront through domain name resolution, then
add the sentence

2022-11-21 13:38 UTC, dengmingtong commented on rfcs/alb_expose_portal/index.md
> +This RFC proposes is to design a new architecture to make service workbench can be deployed and used in china regions without ICP domain.
Add new scenario

2022-11-21 15:20 UTC, dengmingtong commented on rfcs/alb_expose_portal/index.md
> +![existing-deployment](./existing-deployment.drawio.png)
fixed

2022-11-22 03:57 UTC, zxkane approved these changes

2022-11-22 03:57 UTC, merged