enable china customer to configure swb domain
awslabs/service-workbench-on-aws-cn pull request #24
Opened 2022-06-23 06:48 UTC by dengmingtong

Issue #, if available:

Description of changes:

Checklist:

- [yes ] Have you successfully deployed to an AWS account with your changes?
- [ yes] Have you successfully deployed to an AWS China account with your changes?
- [ ] Have you written new tests for your core changes, as applicable?
- [yes ] Have you successfully tested with your changes locally?
- [ ] If new dependencies have been added, have they been pinned to specific versions?
- [ ] Is this change also required on the AWS Solution version?
- [ ] Have you updated openapi.yaml if you made updates to API definition (including add, delete or update parameter and request data schema)?
- [ ] If you had to run manual tests, have you considered automating those tests by adding them to [end-to-end tests](../main/end-to-end-tests/README.md)?
- [ ] If you are updating the changelog and vending out a new release, have you updated versionNumber and versionDate in [.defaults.yml](../main/config/settings/.defaults.yml)

AS review ticket id:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-24 01:51 UTC, zxkane requested changes

2022-06-24 01:51 UTC, zxkane commented on main/solution/infrastructure/config/infra/cloudformation.yml
> +    - !Not [!Equals ['${self:custom.settings.awsRegion}', 'cn-north-1']]
I don't like disable it for all China region deployments. 
Might be introducing a new parameter let customers configure it.
Let's keep the default value as current.

2022-06-26 09:20 UTC, dengmingtong commented on main/solution/infrastructure/config/infra/cloudformation.yml
> +    - !Not [!Equals ['${self:custom.settings.awsRegion}', 'cn-north-1']]
Add new configuration to let customers to configure domain will be handle in R53 or not.

2022-06-26 12:52 UTC, zxkane approved these changes

2022-06-26 12:58 UTC, merged