add chinese doc
awslabs/service-workbench-on-aws-cn pull request #51
Opened 2022-07-19 15:50 UTC by dengmingtong

Issue #, if available:

Description of changes:

Checklist:

- [ ] Have you successfully deployed to an AWS account with your changes?
- [ ] Have you successfully deployed to an AWS China account with your changes?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully tested with your changes locally?
- [ ] If new dependencies have been added, have they been pinned to specific versions?
- [ ] Is this change also required on the AWS Solution version?
- [ ] Have you updated openapi.yaml if you made updates to API definition (including add, delete or update parameter and request data schema)?
- [ ] If you had to run manual tests, have you considered automating those tests by adding them to [end-to-end tests](../main/end-to-end-tests/README.md)?
- [ ] If you are updating the changelog and vending out a new release, have you updated versionNumber and versionDate in [.defaults.yml](../main/config/settings/.defaults.yml)

AS review ticket id:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-20 01:55 UTC, zxkane requested changes
please also add a rendered link in PR's description

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/best_practices/cicd.md
> +```重击
重击？这里通常是脚本名字，不需要翻译

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/best_practices/cicd.md
> +工件S3BucketArn:“*”
配置代码需要翻译？

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/best_practices/cicd.md
> +id: cicd
拿不准的先不翻译了？

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/best_practices/cicd.md
> +在 ` 中创建一个设置文件
没有完整翻译？

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/development/introduction.md
> +```重击
代码部分不用翻译

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/development/introduction.md
> +$ 光盘 -
中断了？

2022-07-20 01:55 UTC, zxkane commented on docs/docs/zh/installation_guide/uninstall.md
> ++ 对于正在运行的工作区，在成功删除堆栈之前手动删除 PVRE 角色添加。
为啥有 PVRE，英文也这样？

2022-07-22 01:00 UTC, dengmingtong commented on docs/docs/zh/best_practices/cicd.md
> +工件S3BucketArn:“*”
Removed chinese best practices doc.

2022-07-22 01:01 UTC, dengmingtong commented on docs/docs/zh/best_practices/cicd.md
> +id: cicd
Removed chinese best practices doc.

2022-07-22 01:01 UTC, dengmingtong commented on docs/docs/zh/best_practices/cicd.md
> +在 ` 中创建一个设置文件
Removed chinese best practices doc.

2022-07-22 01:24 UTC, dengmingtong commented on docs/docs/zh/development/introduction.md
> +```重击
已经修改了

2022-07-22 01:25 UTC, dengmingtong commented on docs/docs/zh/development/introduction.md
> +$ 光盘 -
已经修改了

2022-07-22 01:25 UTC, dengmingtong commented on docs/docs/zh/installation_guide/uninstall.md
> ++ 对于正在运行的工作区，在成功删除堆栈之前手动删除 PVRE 角色添加。
是的，英文里也有
`+ For Workspaces that are running, manually delete the PVRE role additions before the stack is successfully deleted.`

2022-07-22 01:26 UTC, dengmingtong commented on docs/docs/zh/best_practices/cicd.md
> +```重击
Removed chinese best practices doc.

2022-07-28 09:35 UTC, zxkane requested changes
docs/ 是使用 yarn 管理的项目，不应该加入新的 `pakcage-lock.json`

2022-07-28 09:35 UTC, zxkane commented on docs/docs/zh/installation_guide/architecture.md
> +Service Workbench 集成了现有的 AWS 服务，例如 [Amazon CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html)、[AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/
缺少 `集成`

2022-07-28 09:35 UTC, zxkane commented on docs/docs/zh/installation_guide/architecture.md
> +### 主机账户
Hosting account -> `主机账号` 合适吗？

2022-07-28 09:35 UTC, zxkane commented on docs/docs/zh/installation_guide/architecture.md
> +AWS 上的 Service Workbench 可以使用 OIDC IdP 作为身份验证来源。
Cognito 彻底不提了吗？

2022-07-28 09:35 UTC, zxkane commented on docs/docs/zh/installation_guide/installation/pre-installation/oidc-providers.md
> +### (Authing Option) Authing.cn OIDC 客户端
`在Authing.cn创建用户` 是不是应该合并进来？

2022-07-28 09:35 UTC, zxkane commented on docs/docs/zh/installation_guide/installation/pre-installation/oidc-providers.md
> +### (Authing Option) Authing.cn OIDC 客户端
Keycloak, Okta 下同

2022-07-28 09:37 UTC, zxkane requested changes

2022-07-28 09:37 UTC, zxkane commented on docs/docs/user_guide/sidebar/common/studies/introduction.md
> +| **Open Data**            | Service Workbench provides access to [Open Data on AWS](https:// aws.amazon.com/opendata/) data by frequently scanning the set of AWS open datasets and adding new dataset
link is broken, why not finding by the strict mode of docusaurus?

2022-07-29 01:31 UTC, dengmingtong commented on docs/docs/zh/installation_guide/architecture.md
> +Service Workbench 集成了现有的 AWS 服务，例如 [Amazon CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html)、[AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/
Added

2022-07-29 01:32 UTC, dengmingtong commented on docs/docs/zh/installation_guide/architecture.md
> +AWS 上的 Service Workbench 可以使用 OIDC IdP 作为身份验证来源。
在中文版里面把Cognito删掉了。

2022-07-29 01:34 UTC, dengmingtong commented on docs/docs/zh/installation_guide/installation/pre-installation/oidc-providers.md
> +### (Authing Option) Authing.cn OIDC 客户端
在 ### (Authing Option) Authing.cn OIDC 客户端 章节的后面紧接着就是 ### 在Authing.cn创建用户。
两个设定成平行章节
Keycloak, Okta 也一样

2022-07-29 01:55 UTC, dengmingtong commented on docs/docs/zh/installation_guide/architecture.md
> +### 主机账户
修改成 “托管帐户”？

2022-07-29 02:09 UTC, dengmingtong commented on docs/docs/zh/installation_guide/installation/pre-installation/oidc-providers.md
> +### (Authing Option) Authing.cn OIDC 客户端
已经修改

2022-07-29 05:09 UTC, dengmingtong commented on docs/docs/user_guide/sidebar/common/studies/introduction.md
> +| **Open Data**            | Service Workbench provides access to [Open Data on AWS](https:// aws.amazon.com/opendata/) data by frequently scanning the set of AWS open datasets and adding new dataset
It should be docusaurus version issue, I open an [issue](https://github.com/awslabs/service-workbench-on-aws-cn/issues/60) and fix it later.

2022-07-29 07:31 UTC, zxkane reviewed
rendered version still is stale

2022-07-29 08:49 UTC, zxkane approved these changes

2022-07-29 08:50 UTC, merged